print("****************************************************************************")
print("Welcome to the Marvel guess game!!!")
print("A sequel to the infinity war quiz") 
print("In this game you will get 3 clues to which hero or herione I am describing")
print("****************************************************************************")
print("\n")
print("Hero or Heroine 1")
print("\n")
print("Clue 1.This hero bulletproof")
print("\n")
print("Clue 2.His signature weapon are claws")
print("\n")
print("Now for the give away clue")
print("\n")
print("Clue 3.He is the king of an African country")
print("\n")
choice = input("In BLOCK CAPITALS it is: ")
if choice == "BLACK PANTHER" :
    print("Well done, that's right!")
else:
    print("Wrong. The correct answer is BLACK PANTHER!")
print("\n")
