print("******************************************************")
print("Welcome to the sequel to the Avenger Infinity War Quiz")
print("The next best game")
print("The Marvel Guessing Game")
print("*******************************************************")
print("\n")
print("*******************************************************")
print("Hero or heroine 1")
print("*******************************************************")
print("\n")
print("Clue 1. This hero is known to be with the guardians of the galaxy")
print("Clue 2. His first name is Sam")
print("Clue 3. He is known as the Human Rocket")
choice=input("Who is it? Type in a hero to guess!")
if choice.upper().strip() == "NOVA":
    print("Well done, that's right!")
else:
    print("Wrong. The correct answer is Nova!")
print("\n")
print("*******************************************************")
print("Hero or heroine 2")
print("*******************************************************")
print("\n")
print("Clue 1. He brought the avengers together")
print("Clue 2. He is very important at S.H.I.E.L.D")
print("Clue 3. He is a commander on the helicarrier")
choice=input("Who is it? Type in a hero to guess!")
if choice.upper().strip() == "NICK FURY":
    print("Well done, that's right!")
else:
    print("Wrong. The correct answer is Nick fury!")
print("\n")
print("*******************************************************")
print("Hero or heroine 3")
print("*******************************************************")
print("\n")
print("Clue 1. She was trained as an assassin")
print("Clue 2. Her sister hates her")
print("Clue 3. Her Father is the main villian of infinity war")
choice=input("Who is it? Type in a hero to guess!")
if choice.upper().strip() == "GAMORA":
    print("Well done, that's right!")
else:
    print("Wrong. The correct answer is Gamora!")
print("\n")
print("*******************************************************")
print("Hero or heroine 4")
print("*******************************************************")
print("\n")
print("Clue 1. He doesn't have super powers ")
print("Clue 2. He never liked Captain America")
print("Clue 3. He is filthy rich")
choice=input("Who is it? Type in a hero to guess!")
if choice.upper().strip() == "IRON MAN":
    print("Well done, that's right!")
else:
    print("Wrong. The correct answer is Iron Man!")
print("\n")
print("Thank you for playing the Marvel Guessing game")
print("Please play again soon") 

